package processor

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestTranscodeVideoProducesHLSManifest is the first end-to-end test for
// the transcoder. It generates a 5-second synthetic source with ffmpeg's
// lavfi testsrc (no fixture file needed), runs TranscodeVideo, and asserts
// that both the DASH manifest AND the HLS manifest exist on disk.
//
// Skipped when ffmpeg is not in PATH (CI environments may not have it).
func TestTranscodeVideoProducesHLSManifest(t *testing.T) {
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		t.Skip("ffmpeg not in PATH; skipping integration test")
	}

	dir := t.TempDir()
	inputPath := filepath.Join(dir, "testsrc.mp4")
	outputDir := filepath.Join(dir, "out")

	// Generate a 5-second 320x240 30fps test pattern. The encoder settings
	// match the production defaults (libx264, yuv420p) so the HLS remux
	// pass has a valid H.264 stream to wrap.
	genArgs := []string{
		"-y",
		"-f", "lavfi",
		"-i", "testsrc=duration=5:size=320x240:rate=30",
		"-c:v", "libx264",
		"-pix_fmt", "yuv420p",
		"-preset", "ultrafast",
		inputPath,
	}
	genCmd := exec.Command("ffmpeg", genArgs...)
	genCmd.Stderr = os.Stderr
	if err := genCmd.Run(); err != nil {
		t.Fatalf("generate test input: %v", err)
	}

	// Run the production transcoder (DASH + HLS + thumbnail passes).
	result, err := TranscodeVideo(inputPath, outputDir)
	if err != nil {
		t.Fatalf("TranscodeVideo: %v", err)
	}
	if result == nil {
		t.Fatal("TranscodeVideo returned nil result")
	}

	// DASH artifacts (existing behavior, regression guard).
	manifestPath := filepath.Join(outputDir, "manifest.mpd")
	if _, err := os.Stat(manifestPath); err != nil {
		t.Errorf("DASH manifest.mpd missing: %v", err)
	}

	// HLS artifacts (PR #1 acceptance criteria).
	hlsManifest := filepath.Join(outputDir, "master.m3u8")
	if _, err := os.Stat(hlsManifest); err != nil {
		t.Errorf("HLS master.m3u8 missing: %v", err)
	}

	// At least one .ts segment must exist; otherwise the HLS playlist is
	// empty and iOS Safari will fail to start playback.
	tsEntries, err := filepath.Glob(filepath.Join(outputDir, "seg-*.ts"))
	if err != nil {
		t.Fatalf("glob seg-*.ts: %v", err)
	}
	if len(tsEntries) == 0 {
		t.Error("no seg-*.ts segments produced; HLS playlist would be empty")
	}

	// TranscodeResult.HLSManifest should be populated for API consumers.
	if result.HLSManifest == "" {
		t.Error("TranscodeResult.HLSManifest is empty")
	}
	if result.HLSManifest != hlsManifest {
		t.Errorf("TranscodeResult.HLSManifest = %q, want %q", result.HLSManifest, hlsManifest)
	}

	// Thumbnail artifacts (PR #2 acceptance criteria).
	// The sprite is a 10x10 grid of 160x90 tiles = 1600x900 JPEG. Even
	// with a 5s source (1 sampled frame) ffmpeg still produces a full
	// grid; the other 99 cells are blank. We only assert presence + that
	// the file is non-empty (the spec says "Files written").
	thumbSprite := filepath.Join(outputDir, "thumbnails.jpg")
	thumbSpriteInfo, err := os.Stat(thumbSprite)
	if err != nil {
		t.Errorf("thumbnails.jpg missing: %v", err)
	} else if thumbSpriteInfo.Size() == 0 {
		t.Error("thumbnails.jpg is empty")
	}

	// The VTT pointer file is generated by Go (no FFmpeg). It must
	// exist, start with the WEBVTT header, and contain at least one
	// #xywh= cue.
	thumbVTT := filepath.Join(outputDir, "thumbnails.vtt")
	vttBytes, err := os.ReadFile(thumbVTT)
	if err != nil {
		t.Fatalf("thumbnails.vtt missing: %v", err)
	}
	vtt := string(vttBytes)
	if len(vtt) < 10 || vtt[:6] != "WEBVTT" {
		t.Errorf("thumbnails.vtt missing WEBVTT header, got %q", vtt[:min(20, len(vtt))])
	}
	if !strings.Contains(vtt, "#xywh=") {
		t.Error("thumbnails.vtt has no #xywh= cues; sprite wiring is broken")
	}
	if !strings.Contains(vtt, "thumbnails.jpg#xywh=0,0,160,90") {
		t.Error("thumbnails.vtt should contain first cue at tile (0,0)")
	}

	// TranscodeResult should advertise both artifact paths.
	if result.ThumbnailSprite != thumbSprite {
		t.Errorf("TranscodeResult.ThumbnailSprite = %q, want %q", result.ThumbnailSprite, thumbSprite)
	}
	if result.ThumbnailVTT != thumbVTT {
		t.Errorf("TranscodeResult.ThumbnailVTT = %q, want %q", result.ThumbnailVTT, thumbVTT)
	}
}

// TestGenerateThumbnailsVTT is a fast unit test for the pure-Go VTT
// generator. It covers the math + clock formatting without spinning up
// ffmpeg, so it runs in microseconds and stays green even in ffmpeg-less CI.
func TestGenerateThumbnailsVTT(t *testing.T) {
	cases := []struct {
		name     string
		duration float64
		// wantCues: how many #xywh cues we expect (1 per 5s, min 1).
		wantCues int
		// wantFirstXY: the (x,y) of the first cue (proves grid math starts at 0,0).
		wantFirstXY string
		// wantLastEnd: the timestamp at the end of the last cue.
		wantLastEnd string
	}{
		// floor(d/5) cues, clamped to >= 1.
		{"zero duration", 0, 1, "0,0", "00:00:00.000"},
		{"short below one sample (3s)", 3, 1, "0,0", "00:00:03.000"},
		{"exact 5s one sample", 5, 1, "0,0", "00:00:05.000"},
		{"11s two samples, second tile in col1", 11, 2, "0,0", "00:00:10.000"},
		{"100s twenty samples (1 per 5s)", 100, 20, "0,0", "00:01:40.000"},
		{"500s exactly = 100 samples fills grid", 500, 100, "0,0", "00:08:20.000"},
		{"505s = 101 samples (one past grid end)", 505, 101, "0,0", "00:08:25.000"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := GenerateThumbnailsVTT(tc.duration)
			if !strings.HasPrefix(got, "WEBVTT") {
				t.Errorf("missing WEBVTT header in: %q", got[:min(20, len(got))])
			}
			cues := strings.Count(got, "#xywh=")
			if cues != tc.wantCues {
				t.Errorf("cue count = %d, want %d", cues, tc.wantCues)
			}
			if !strings.Contains(got, "#xywh="+tc.wantFirstXY+",160,90") {
				t.Errorf("first cue should be at %q; body=%q", tc.wantFirstXY, got)
			}
			// Find the LAST ' --> ' separator; everything up to the next
			// newline is the end timestamp of the last cue. This is more
			// robust than splitting on '\n--> ' which is offset by one
			// and would actually pick the start of the last cue.
			const sep = " --> "
			lastSep := strings.LastIndex(got, sep)
			if lastSep < 0 {
				t.Fatalf("malformed VTT body, no %q separator: %q", sep, got)
			}
			rest := got[lastSep+len(sep):]
			lastEnd := strings.SplitN(rest, "\n", 2)[0]
			if lastEnd != tc.wantLastEnd {
				t.Errorf("last cue end = %q, want %q", lastEnd, tc.wantLastEnd)
			}
		})
	}
}

// TestFormatVTTTimestamp covers the clock-formatting edge cases that the
// generator relies on (sub-second precision, no 60s overflow, no negative).
func TestFormatVTTTimestamp(t *testing.T) {
	cases := []struct {
		sec  float64
		want string
	}{
		{-1, "00:00:00.000"},
		{0, "00:00:00.000"},
		{0.001, "00:00:00.001"},
		{5, "00:00:05.000"},
		{59.999, "00:00:59.999"},
		{60, "00:01:00.000"},
		{3599.5, "00:59:59.500"},
		{3600, "01:00:00.000"},
		{3601.234, "01:00:01.234"},
	}
	for _, tc := range cases {
		if got := formatVTTTimestamp(tc.sec); got != tc.want {
			t.Errorf("formatVTTTimestamp(%v) = %q, want %q", tc.sec, got, tc.want)
		}
	}
}
